[package]
name = "taurus-db"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tasql"
path = "src/bin/tasql.rs"

[dependencies]
anyhow = "1.0.70"
console = "0.15.5"
tokio = { version = "1.26.0", features = ["rt", "macros", "rt-multi-thread"] }
